import apiClient from '@/src/api/apiClient';
import { API_BASE_URL } from '@/src/config/config';
import {
    AuthClient,
    BuildingsClient,
    ChatClient,
    FilesClient,
    FloorplansClient,
    GradesClient,
    GroupsClient,
    MapsClient,
    NewsClient,
    OrganizationsClient,
    RoomsClient,
    ScheduleClient,
    TasksClient,
    ToolsClient,
    UsersClient
} from './generatedClient'; // Path to your NSwag file

export {
    appendFileParameterForReactNative,
    fileParameterFromPickedImage,
} from './rnMultipart';
export {
    createFloorForBuildingMultipart,
    uploadFloorplanMultipart,
} from './multipartMapEndpoints';

// This interface matches the shape of the ServiceResponse generated by NSwag
interface IServiceResponse<T> {
    isSuccess?: boolean;
    data?: T;
    error?: { message?: string; code?: string; detail?: string } | null | any;
}

/** Structured API error after parsing JSON bodies (middleware, BadRequest ServiceResponse, etc.). */
export type ParsedApiError = {
    code?: string;
    message: string;
    detail?: string;
    httpStatus?: number;
};

const GENERIC = 'Something went wrong. Please try again.';

function readString(obj: Record<string, unknown>, ...keys: string[]): string | undefined {
    for (const k of keys) {
        const v = obj[k];
        if (typeof v === 'string' && v.trim()) return v.trim();
    }
    return undefined;
}

/** Pull `error` / `Error` node from a JSON object. */
function pickErrorNode(o: Record<string, unknown>): Record<string, unknown> | null {
    const e = o.error ?? o.Error;
    if (e && typeof e === 'object' && !Array.isArray(e)) return e as Record<string, unknown>;
    return null;
}

/**
 * Parse backend `ServiceResponse` error, `ExceptionHandlingMiddleware` payload, or ProblemDetails-like shapes.
 */
export function parseServiceErrorFromBody(body: unknown): ParsedApiError | null {
    if (body == null) return null;
    if (typeof body === 'string') {
        const t = body.trim();
        if (!t) return null;
        try {
            return parseServiceErrorFromBody(JSON.parse(t));
        } catch {
            return t.length < 1200 ? { message: t } : { message: t.slice(0, 1197) + '…' };
        }
    }
    if (typeof body !== 'object' || body === null) return null;
    const o = body as Record<string, unknown>;

    const errNode = pickErrorNode(o);
    if (errNode) {
        const code = readString(errNode, 'code', 'Code');
        const message = readString(errNode, 'message', 'Message') ?? 'Request failed.';
        const detail = readString(errNode, 'detail', 'Detail');
        if (code || message !== 'Request failed.' || detail) {
            return { code, message, detail };
        }
    }

    const detail = readString(o, 'detail', 'Detail');
    const title = readString(o, 'title', 'Title');
    const msg = readString(o, 'message', 'Message');
    if (detail || title || msg) {
        return { message: msg ?? title ?? 'Request failed.', detail: detail ?? undefined, code: readString(o, 'code', 'Code') };
    }

    if (o.errors && typeof o.errors === 'object') {
        const errs = o.errors as Record<string, unknown>;
        const parts: string[] = [];
        for (const v of Object.values(errs)) {
            if (Array.isArray(v)) {
                for (const x of v) {
                    if (typeof x === 'string') parts.push(x);
                }
            } else if (typeof v === 'string') {
                parts.push(v);
            }
        }
        if (parts.length) return { message: parts.join(' ') };
    }

    return null;
}

/** Single string for `Alert.alert` / toasts: includes code and optional dev `detail`. */
export function formatParsedApiError(p: ParsedApiError, options?: { maxDetailLength?: number }): string {
    const maxD = options?.maxDetailLength ?? 3500;
    const head = p.code ? `[${p.code}] ${p.message}` : p.message;
    if (!p.detail?.trim()) return head;
    const d = p.detail.trim();
    const clipped = d.length > maxD ? d.slice(0, maxD) + '…' : d;
    return `${head}\n\n---\n${clipped}`;
}

/**
 * Reads a user-facing message from backend `ServiceResponse` / `ExceptionHandlingMiddleware`,
 * ASP.NET validation (`errors`), ProblemDetails, or NSwag `ApiException.response` (string or parsed JSON).
 */
export function getApiErrorMessage(error: unknown): string {
    const parts = getApiErrorParts(error);
    return formatParsedApiError(parts);
}

/** Full structured error (code, message, detail, HTTP status when available). */
export function getApiErrorParts(error: unknown): ParsedApiError {
    if (error == null) return { message: GENERIC };

    const anyErr = error as Record<string, unknown> & {
        isAxiosError?: boolean;
        isApiException?: boolean;
        response?: unknown;
        message?: string;
        status?: number;
    };

    if (typeof anyErr.message === 'string' && anyErr.message.includes('Session expired')) {
        return { message: anyErr.message };
    }

    const httpFromAxios = (anyErr as { response?: { status?: number; data?: unknown } }).response?.status;

    const FORBIDDEN_SCHEDULE_HINT =
        'You don’t have permission. Creating events or booking rooms requires schedule edit access for your role in this organization.';

    if (anyErr.isAxiosError) {
        const data = (anyErr as { response?: { data?: unknown } }).response?.data;
        const parsed = parseServiceErrorFromBody(data);
        if (parsed) return { ...parsed, httpStatus: httpFromAxios };
        if (httpFromAxios === 403) {
            return { message: FORBIDDEN_SCHEDULE_HINT, httpStatus: 403 };
        }
    }

    if (anyErr.isApiException === true) {
        const parsed = parseServiceErrorFromBody(anyErr.response);
        if (parsed) return { ...parsed, httpStatus: anyErr.status };
        if (anyErr.status === 403) {
            return { message: FORBIDDEN_SCHEDULE_HINT, httpStatus: 403 };
        }
    }

    if (error instanceof Error && typeof anyErr.message === 'string') {
        if (anyErr.message !== 'An unexpected server error occurred.') {
            return { message: anyErr.message };
        }
    }

    const fromNestedData = parseServiceErrorFromBody((anyErr as { response?: { data?: unknown } }).response?.data);
    if (fromNestedData) return { ...fromNestedData, httpStatus: httpFromAxios ?? anyErr.status };

    const fromLoose = parseServiceErrorFromBody(anyErr.response);
    if (fromLoose) return { ...fromLoose, httpStatus: anyErr.status };

    return { message: GENERIC, httpStatus: httpFromAxios ?? anyErr.status };
}

export const unwrap = async <T>(apiPromise: Promise<IServiceResponse<T>>): Promise<T> => {
    try {
        const response = await apiPromise;

        if (response && response.isSuccess === false) {
            const e = response.error as { code?: string; message?: string; detail?: string } | null | undefined;
            const parsed: ParsedApiError = {
                code: e?.code,
                message: e?.message?.trim() || 'Operation failed.',
                detail: e?.detail?.trim(),
            };
            throw new Error(formatParsedApiError(parsed));
        }

        if (response.data === undefined) {
            throw new Error('Response contained no data.');
        }

        return response.data;
    } catch (error: unknown) {
        throw new Error(getApiErrorMessage(error));
    }
};

// Export ready-to-use instances of your endpoints!
export const authApi = new AuthClient(API_BASE_URL, apiClient);
export const buildingsApi = new BuildingsClient(API_BASE_URL, apiClient);
export const chatApi = new ChatClient(API_BASE_URL, apiClient);
export const filesApi = new FilesClient(API_BASE_URL, apiClient);
export const floorplansApi = new FloorplansClient(API_BASE_URL, apiClient);
export const gradesApi = new GradesClient(API_BASE_URL, apiClient);
export const groupsApi = new GroupsClient(API_BASE_URL, apiClient);
export const mapsApi = new MapsClient(API_BASE_URL, apiClient);
export const newsApi = new NewsClient(API_BASE_URL, apiClient);
export const orgApi = new OrganizationsClient(API_BASE_URL, apiClient);
export const roomsApi = new RoomsClient(API_BASE_URL, apiClient);
export const scheduleApi = new ScheduleClient(API_BASE_URL, apiClient);
export const tasksApi = new TasksClient(API_BASE_URL, apiClient);
export const toolsApi = new ToolsClient(API_BASE_URL, apiClient);
export const usersApi = new UsersClient(API_BASE_URL, apiClient);
