export * from './components/AssignmentsWidget';
export * from './components/AttendanceWidget';
export * from './components/ChatWidget';
export * from './components/GradesWidget';
export * from './components/MapWidget';
export * from './components/NewsWidget';
export * from './components/ScheduleWidget';
export * from './components/TasksWidget';
export * from './components/UsersWidget';