import { StyleSheet } from 'react-native';

export const createStyles = (colors: any) => StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 10 },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: colors.text },
  headerSubtitle: { fontSize: 14, color: colors.subtle, marginTop: 4 },
  listContent: { paddingHorizontal: 20, paddingBottom: 100 },
  sectionHeader: { fontSize: 14, fontWeight: 'bold', color: colors.subtle, marginTop: 24, marginBottom: 12, textTransform: 'uppercase' },
  taskItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card, padding: 16, borderRadius: 12, marginBottom: 10, borderWidth: 1, borderColor: colors.border },
  taskContent: { flex: 1, marginLeft: 12 },
  taskTitle: { fontSize: 16, color: colors.text, fontWeight: '500' },
  taskTitleCompleted: { color: colors.subtle, textDecorationLine: 'line-through' },
  taskMeta: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  taskDate: { fontSize: 12, marginLeft: 4 },
  inputWrapper: { backgroundColor: colors.card, borderTopWidth: 1, borderTopColor: colors.border, padding: 16, paddingBottom: 40 },
  inputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.background, borderRadius: 24, paddingHorizontal: 16, paddingVertical: 8, borderWidth: 1, borderColor: colors.border },
  input: { flex: 1, fontSize: 16, color: colors.text, maxHeight: 100, paddingVertical: 8 },
  dateButton: { padding: 8, marginRight: 4 },
  sendButton: { padding: 8, backgroundColor: colors.primary, borderRadius: 20, marginLeft: 8 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: colors.card, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20 },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: colors.text, marginBottom: 16 },
  dateOption: { flexDirection: 'row', alignItems: 'center', paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: colors.border },
  dateOptionText: { fontSize: 16, color: colors.text, marginLeft: 12 },
  cancelButton: { marginTop: 16, alignItems: 'center', padding: 12 },
  cancelText: { color: colors.notification, fontWeight: 'bold', fontSize: 16 },
  listSelector: { paddingHorizontal: 20, marginBottom: 16 },
  listChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, marginRight: 8, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border },
  listChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  listChipText: { color: colors.text, fontWeight: '600' },
  listChipTextActive: { color: '#fff' },
});
